name: oci-resource-manager-build-demo
on:
  push:
    branches:
      - github-actions-resource-manager
jobs:
  build-resource-manager:
    name: Build Resource Manager
    runs-on: ubuntu-latest
    env:
        STACK_NAME: "OCI Resource Manager Demo Stack"
        PROVIDER_NAME: "GitHub Source Provider"
        BRANCH_NAME: "github-actions-resource-manager"
        REPO_URL: "https://github.com/recursivecodes/oci-resource-manager-demo"
        TF_VERSION: "0.13.x"
        REGION: "us-phoenix-1"
        BUCKET_NAME: "test_bucket"
    steps: