name: oci-resource-manager-build-demo
on:
  push:
    branches:
      - github-actions-resource-manager
jobs:
  build-resource-manager:
    name: Build Resource Manager
    runs-on: ubuntu-latest
    env:
        STACK_NAME: "OCI Resource Manager Demo Stack"
        PROVIDER_NAME: "GitHub Source Provider"
        BRANCH_NAME: "github-actions-resource-manager"
        REPO_URL: "https://github.com/recursivecodes/oci-resource-manager-demo"
        TF_VERSION: "0.13.x"
        REGION: "us-phoenix-1"
        BUCKET_NAME: "test_bucket"
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Write Config & Key Files'
      run: |
        mkdir ~/.oci
        echo "[DEFAULT]" >> ~/.oci/config
        echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
        echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
        echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config
        echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
        echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
        echo "key_file=~/.oci/key.pem" >> ~/.oci/config
        echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
        
    - name: 'Fix OCI Config File Permissions'
      run: |
        oci setup repair-file-permissions --file /home/runner/.oci/config
        oci setup repair-file-permissions --file /home/runner/.oci/key.pem