name: OCI Resource Manager Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Oracle Cloud CLI
      uses: oracle-actions/run-oci-cli-command@v1.1.1
      with:
        config-file: ${{ github.workspace }}/oci/config
        tenancy: ${{ secrets.OCI_TENANCY_OCID }}
        user: ${{ secrets.OCI_USER_OCID }}
        fingerprint: ${{ secrets.OCI_FINGERPRINT }}
        private-key: ${{ secrets.OCI_KEY_FILE }}
        command: oci resource-manager stack list --compartment-id ocid1.compartment.oc1..aaaaaaaaw5uvqadwjql5fakqovf6jlc7sb5yvdnvwuxr7xreliqow7lhe7na
